controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
fruits:
    path: /fruits
    controller: App\Controller\FruitController::index